
package org.surthi.app.ws.moderate.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version:
 * 2.2
 * 
 */
@WebService(name = "TeamServer", targetNamespace = "http://moderate.ws.app.surthi.org/")
@XmlSeeAlso({ObjectFactory.class})
public interface TeamServer {


  /**
   * 
   * @param arg0
   * @return returns client.Team
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getTeam", targetNamespace = "http://moderate.ws.app.surthi.org/",
      className = "org.surthi.app.ws.moderate.client.GetTeam")
  @ResponseWrapper(localName = "getTeamResponse",
      targetNamespace = "http://moderate.ws.app.surthi.org/",
      className = "org.surthi.app.ws.moderate.client.GetTeamResponse")
  @Action(input = "http://moderate.ws.app.surthi.org/TeamServer/getTeamRequest",
      output = "http://moderate.ws.app.surthi.org/TeamServer/getTeamResponse")
  Team getTeam(@WebParam(name = "arg0", targetNamespace = "") String arg0);

  /**
   * 
   * @return returns java.util.List<client.Team>
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getTeams", targetNamespace = "http://moderate.ws.app.surthi.org/",
      className = "org.surthi.app.ws.moderate.client.GetTeams")
  @ResponseWrapper(localName = "getTeamsResponse",
      targetNamespace = "http://moderate.ws.app.surthi.org/",
      className = "org.surthi.app.ws.moderate.client.GetTeamsResponse")
  @Action(input = "http://moderate.ws.app.surthi.org/TeamServer/getTeamsRequest",
      output = "http://moderate.ws.app.surthi.org/TeamServer/getTeamsResponse")
  List<Team> getTeams();

}
